Avoid DateTime::__construct fatal error
From previous commit, when running all_integration_tests.php, was getting:
Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting...

The DateTime construct error was happening because in ThinkUpController, SessionCache::init was being called in ``__construct``, before ``initializeApp``` is called in ``go``. The default timezone is set in ``initializeApp``.

Moved date_default_timezone_set($config->getValue('timezone')); before SessionCache::init call.